apiVersion: v1
kind: Pod
metadata:
     name: app-pod
     labels:
        quota: pod-level
spec:
    containers:
    - name: nginx-container
      image: nginx:latest
      resources:
         requests:
             memory: "64Mi"
             cpu: "250m"
         limits:
                memory: "128Mi"
                cpu: "500m"
    - name: db
      image: mysql:5.6
      env:
          - name: MYSQL_ROOT_PASSWORD
            value: "redhat"
      resources:
         requests:
             memory: "1028Mi"
             cpu: "1"
         limits:
             memory: "2048Mi"
             cpu: "2"
